#!/bin/bash
pip install --upgrade pip
pip install torch==2.3.1  # Pastikan versi torch sesuai
pip install git+https://github.com/facebookresearch/detectron2.git
python -c "import detectron2; print('Detectron2 version:', detectron2.__version__)"
